name: flutter_simple_treeview
version: 3.0.1
description: >
  A widget, that visualises a tree structure, where a node can be any widget.
repository: https://github.com/google/flutter.widgets/tree/master/packages/flutter_simple_treeview

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
