name: gallery
version: 0.1.0
description: Example gallery for the flutter_widgets package.

environment:
  sdk: ^2.0.0

dependencies:
  flutter_widgets:
    path: ../
  intl: ^0.16.0
  meta: ^1.1.1

dev_dependencies:
  file: ^5.0.0
  flutter_driver:
    sdk: flutter
  path: ^1.5.1
  test: ^1.3.0

flutter:
  uses-material-design: true
