name: scrollable_positioned_list
version: 0.1.8
description: >
  A list with helper methods to programmatically scroll to an item.
homepage: https://github.com/google/flutter.widgets

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ^1.12.13+hotfix.5

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.1

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
