name: scrollable_positioned_list
version: 0.2.3
description: >
  A list with helper methods to programmatically scroll to an item.
homepage: https://github.com/google/flutter.widgets/tree/master/packages/scrollable_positioned_list

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.13.8'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.10.0-0
  flutter_test:
    sdk: flutter
