name: self_storing_input
version: 4.0.0-nullsafety.0
description: >
  A set of input widgets that automatically save and load
  the entered value to a data store.
homepage: https://github.com/google/flutter.widgets

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ^1.12.13+hotfix.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
